#!/usr/bin/env python3
"""Render the parity documents from the extracted data.

Hand-written inventories go stale the day a route is added, so every number in
these documents comes from the extractors. Regenerate rather than edit.
"""

from __future__ import annotations

import collections
import json
import pathlib
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
HERE = pathlib.Path(__file__).resolve().parent
SNAPSHOT = HERE / "url_map_snapshot.json"

HTML_HELPERS = {
    "pulse_social_shell", "admin_page_html", "arena_page_shell", "render_account_page",
    "arena_simple_page", "render_seo_landing", "pulse_page_html", "dashboard_network_shell",
    "dashboard_creator_shell", "pulse_security_settings_page", "trust_public_page",
    "dashboard_account_shell", "render_ads_landing_page", "education_shell",
    "education_feature_page", "dashboard_creator_subsystem_page", "render_template",
    "_verification_admin_shell", "search_pages", "pulse_gateway_card_html",
}

BANNER = (
    "<!-- Generated by scripts/parity/render_reports.py. Do not edit by hand;\n"
    "     regenerate after changing routes, navigation, or linking. -->\n"
)


def run(script: str, *args: str) -> object:
    result = subprocess.run(
        [sys.executable, str(HERE / script), *args],
        capture_output=True, text=True, check=True, cwd=str(REPO_ROOT),
    )
    return json.loads(result.stdout)


def native_doc(native: dict) -> str:
    rows = []
    links = native["links"]
    for action in native["master_navigation"]:
        rows.append((action["section"], action["label"], action["route"], action["status"], action["description"]))
    body = [
        BANNER,
        "# PulseSoc Native Product Inventory\n",
        f"- Screens registered in navigators: **{len(native['screens'])}**",
        f"- `*Screen.tsx` files: **{len(native['screen_files'])}**",
        f"- Screens with a `pulsesoc.com` deep link: **{len(links)}**",
        f"- Master-navigation destinations: **{len(native['master_navigation'])}**\n",
        "`linking.ts` sets `prefixes: [\"pulsesoc://\", \"https://pulsesoc.com\"]`, so every",
        "path below is simultaneously a native deep link and a URL the website must answer.\n",
        "## Master navigation (canonical destinations)\n",
        "| Section | Destination | Route | Status | Purpose |",
        "| --- | --- | --- | --- | --- |",
    ]
    for section, label, route, status, desc in rows:
        body.append(f"| {section} | {label} | `{route}` | {status} | {desc} |")
    body += ["", "## Deep-linked screens\n", "| Screen | Deep-link path |", "| --- | --- |"]
    for screen, path in sorted(links.items()):
        body.append(f"| {screen} | `/{path}` |")
    return "\n".join(body) + "\n"


def web_doc(web: list[dict], url_map: list[str]) -> str:
    rules = {r["rule"] for r in web}
    pages = {r["rule"] for r in web if r["templates"] or (set(r["calls"]) & HTML_HELPERS)}
    admin = {r for r in pages if r.startswith("/admin") or "/admin" in r}
    api = {r["rule"] for r in web if r["jsonify"] or r["rule"].startswith("/api")}
    templates = collections.Counter(t for r in web for t in r["templates"])
    body = [
        BANNER,
        "# PulseSoc Web Product Inventory\n",
        f"- Rules in the booted Flask `url_map`: **{len(url_map)}** (authoritative)",
        f"- Rules visible to static analysis: **{len(rules)}**",
        f"  - the difference is blueprint route packs registered inside `except Exception`",
        f"- Rules that render an HTML page: **{len(pages)}**",
        f"  - admin: **{len(admin)}**, user-facing: **{len(pages - admin)}**",
        f"- JSON/API rules: **{len(api)}**",
        f"- Jinja templates: **{len(list((REPO_ROOT / 'templates').glob('*.html')))}**\n",
        "Most web pages are not Jinja templates; they are assembled by Python HTML",
        "helpers in `bot.py`. The shell helpers, by route count:\n",
        "| Helper | Rules |",
        "| --- | --- |",
    ]
    helper_counts = collections.Counter()
    for r in web:
        for call in set(r["calls"]) & HTML_HELPERS:
            helper_counts[call] += 1
    for helper, count in helper_counts.most_common():
        body.append(f"| `{helper}` | {count} |")
    body += ["", "## Jinja templates\n", "| Template | Rules rendering it |", "| --- | --- |"]
    for name, count in templates.most_common():
        body.append(f"| `{name}` | {count} |")
    return "\n".join(body) + "\n"


def matrix_doc(matrix: list[dict]) -> str:
    counts = collections.Counter(r["parity"] for r in matrix)
    body = [
        BANNER,
        "# PulseSoc Web ↔ Native Parity Matrix\n",
        "Existence is judged against the booted Flask `url_map`; render behaviour",
        "comes from the handler AST. Classification:\n",
        "- **PARITY** — a web rule matches and serves an HTML page.",
        "- **REDIRECT_ONLY** — a web rule matches but only redirects.",
        "- **BLUEPRINT_UNVERIFIED** — the rule exists but its handler was not",
        "  statically reachable, so the response type is unconfirmed.",
        "- **MISSING** — no web rule matches. A shared `https://pulsesoc.com`",
        "  link 404s: there is no catch-all rule and no 404 handler.\n",
        "## Totals\n",
        "| Verdict | Count |",
        "| --- | --- |",
    ]
    for verdict, count in counts.most_common():
        body.append(f"| {verdict} | {count} |")
    body += ["", "## Every destination\n",
             "| Source | Destination | Native route | Verdict | Web rule |",
             "| --- | --- | --- | --- | --- |"]
    for row in sorted(matrix, key=lambda r: (r["parity"] != "MISSING", r["native_route"])):
        served = ", ".join(f"`{r}`" for r in row["web_rules"][:2]) or "—"
        body.append(
            f"| {row['source']} | {row['id']} | `{row['native_route']}` | {row['parity']} | {served} |"
        )
    return "\n".join(body) + "\n"


def main() -> int:
    native = run("extract_native_surfaces.py")
    web = run("extract_web_routes.py")
    url_map = json.loads(SNAPSHOT.read_text())
    matrix = run("build_parity_matrix.py", "--url-map", str(SNAPSHOT))["matrix"]

    outputs = {
        "PULSESOC_NATIVE_PRODUCT_INVENTORY.md": native_doc(native),
        "PULSESOC_WEB_PRODUCT_INVENTORY.md": web_doc(web, url_map),
        "PULSESOC_WEB_NATIVE_PARITY_MATRIX.md": matrix_doc(matrix),
    }
    target = REPO_ROOT / "docs" / "parity"
    target.mkdir(parents=True, exist_ok=True)
    for name, text in outputs.items():
        (target / name).write_text(text, encoding="utf-8")
        print(f"wrote docs/parity/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
