"""Seller groups for the cart, and the questions each group still has to ask.

Why the cart is grouped at all
------------------------------
``POST /api/pulse/marketplace/cart/checkout`` takes a ``seller_user_id`` and
settles *one* seller's lines as *one* Stripe charge. Everything it refuses, it
refuses for the whole group: one sold-out line blocks the group, one
unconfirmed price change blocks the group, two currencies in the group are
refused outright, and a booking may not share a basket with anything else.

A cart page that prints a single cross-seller subtotal of the lines that happen
to be individually purchasable therefore states something the checkout lane will
not honour. It implies "pay for these six" where the server offers "pay for
these two, then these three, and not that one at all". This module computes the
groups the server actually transacts in, so the page can offer one pay button
per group and disable it with the server's own reason instead of discovering
that reason as a 409 after the buyer commits.

Why the *questions* are computed here and not in the browser
------------------------------------------------------------
Before it will create a session, the checkout lane demands a lane answer for an
undecided kind, and then buyer details for the resolved kind —
:func:`marketplace_fulfillment.validate_details` refuses a shipping group with no
address, and the field list differs per kind and, for event tickets, per
listing. A browser that rendered that form from its own copy of the field table
would be a third copy of it (``mobile-native``'s
``marketplaceFulfillment.ts`` is the second, and says so). So the server answers
with the form, generated by :func:`marketplace_fulfillment.buyer_form`, and the
browser renders what it is given and names no field itself.

What this module deliberately does not do
-----------------------------------------
It computes no price the server would not charge, and it never widens what the
server allows. Every refusal it reports is re-derived by the checkout lane on the
way through; this is a pre-flight, not an authority. When the two could
disagree, the group is reported *unpayable* — a page that greys out a button the
server would have honoured costs a buyer one extra tap, and a page that offers
one the server refuses costs them their confidence.

Flask-free and ``bot``-free on purpose, like ``marketplace_web`` and
``marketplace_storefront``: its test suite needs no database and no app boot.
"""

from __future__ import annotations

from typing import Any, Iterable, Mapping, Sequence

from services import marketplace_fulfillment as fulfillment

#: Line states that stop the *whole* group. Deliberately the same three words
#: ``cart_checkout`` blocks on, and spelled as a positive set rather than as an
#: inverse of "the states that buy", so a state neither this file nor the lane has
#: heard of is treated the same way by both. Widening it here would grey out a
#: button the server would have honoured; narrowing it would offer one the server
#: refuses. The refusal belongs to the lane; this only reports it early.
BLOCKING_STATES = frozenset({"sold", "removed", "restricted"})

#: Fulfilment kinds a browser can collect the answers for today. Shipping and
#: pickup ask for contact and address fields, which are ordinary form inputs, and
#: a digital line asks for nothing at all. The rest need a date, a time and a
#: timezone picker against the seller's published availability — a scheduler, not
#: a form — and the app already has one. Offering a half-built date field here
#: would take money for a booking at a time the seller never offered.
BROWSER_KINDS = frozenset({"shipping", "pickup", "shipping_or_pickup", "digital"})

#: Said to the buyer when a group needs the app. Names the working path rather
#: than apologising for the missing one.
BROWSER_UNSUPPORTED = (
    "Services, events and bookings are scheduled in the PulseSoc app, where the "
    "same cart is waiting."
)


def scheduled_kinds(line_kinds: Iterable[str]) -> list[str]:
    """The kinds in a group that need a moment in time as well as a price.

    The prefix test is deliberately narrowed by ``UNDECIDED_KINDS``, and not for
    tidiness: ``service_choice`` begins with ``service_`` and is not a service —
    it is the *question* of whether a service is delivered remotely or on site,
    and only one of those two answers is scheduled. ``cart_checkout`` calls this
    with kinds that ``resolve_choice`` has already settled, so it never sees the
    word; :func:`group_lines` works from the cart's raw kinds and does, and
    without this it reported an undecided service as a booking and told the buyer
    to check out one at a time when the real refusal was that the group asks two
    questions at once.
    """
    return [k for k in line_kinds
            if str(k or "").startswith(("service_", "booking_", "event_"))
            and str(k or "") not in fulfillment.UNDECIDED_KINDS]


def details_kind_for(line_kinds: Sequence[str]) -> str:
    """Whose questions the whole group is asked, given each line's resolved kind.

    A group settles against one set of buyer details, so one kind's field list
    has to stand for all of them. An address wins, because something in the
    basket travels and a parcel with no street is undeliverable; failing that a
    scheduled line wins, because it needs a time; failing that pickup, which
    needs a name and a phone so the seller can hand the thing over. An
    all-digital group is asked nothing.

    Extracted from ``marketplace_cart_routes.cart_checkout``, which now calls it,
    so the form the buyer fills in is built from the same rule that decides which
    submission is accepted.
    """
    kinds = [str(k or "") for k in line_kinds]
    kind = next((k for k in kinds if fulfillment.needs_shipping_address(k)), "")
    if not kind:
        scheduled = scheduled_kinds(kinds)
        if scheduled:
            kind = scheduled[0]
    if not kind:
        kind = next((k for k in kinds if k == "pickup"), "")
    return kind


def _minor(value: Any) -> int:
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        return 0


def _qty(value: Any) -> int:
    try:
        return max(1, int(value or 1))
    except (TypeError, ValueError):
        return 1


def _line_kind(line: Mapping[str, Any]) -> str:
    return str(line.get("fulfillment_kind") or "shipping")


def _forms_for(lines: Sequence[Mapping[str, Any]], lane_kind: str) -> dict[str, Any]:
    """The buyer form for each answer the lane question accepts.

    Keyed by the answer rather than by the resolved kind, because the answer is
    what the browser holds and what it posts back. A decided group has the single
    key ``""`` — no question was asked, so there is no answer to key it by.
    """
    # The metadata argument mirrors the checkout lane exactly: ticket tiers are a
    # property of one listing, so they are only offered when the group *is* one
    # listing. A two-line group is asked the kind's fields without them, and the
    # lane agrees, because it passes the same `{}`.
    metadata = dict(lines[0].get("listing_metadata") or {}) if len(lines) == 1 else {}
    answers = [o["value"] for o in fulfillment.lane_options(lane_kind)] or [""]
    forms: dict[str, Any] = {}
    for answer in answers:
        resolved = []
        for line in lines:
            kind, lane_error = fulfillment.resolve_choice(_line_kind(line), answer)
            if lane_error:
                # Still undecided under this answer, which happens when a group
                # mixes two different undecided kinds. The page cannot ask two
                # questions with one control, so the group is handed to the app.
                return {}
            resolved.append(kind)
        details = details_kind_for(resolved)
        forms[answer] = {
            "details_kind": details,
            "fields": [dict(f) for f in fulfillment.buyer_form(details, metadata)],
        }
    return forms


def _lane_question(lines: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    """The one lane question a group may carry, or ``{}`` if it carries none."""
    undecided = {_line_kind(l) for l in lines} & set(fulfillment.UNDECIDED_KINDS)
    if len(undecided) != 1:
        # Zero: nothing to ask. Two: two questions, and one control cannot ask
        # both — reported as unanswerable below rather than guessed at.
        return {}
    kind = next(iter(undecided))
    return {"kind": kind, "options": [dict(o) for o in fulfillment.lane_options(kind)]}


def group_lines(
    lines: Iterable[Mapping[str, Any]], *, can_pay: bool = True
) -> list[dict[str, Any]]:
    """Cart lines -> one entry per seller, in the order the seller first appears.

    First-appearance order rather than a sort: the cart is already ordered by
    when each line was added, and re-sorting by store name would move a group
    the buyer is looking at when an unrelated line arrives.

    ``can_pay`` is false for a guest. A visitor now gets a real cart of their
    own and can fill it, but ``cart_checkout`` still opens with
    ``_require_user()``, so the pre-flight has to report that refusal like any
    other -- the alternative is a pay button that 401s, which is the thing this
    module exists to prevent. A parameter rather than something derived here
    because this module is deliberately Flask-free and knows nothing about
    sessions.
    """
    order: list[int] = []
    buckets: dict[int, list[Mapping[str, Any]]] = {}
    for line in lines:
        seller = _minor(line.get("seller_user_id"))
        if seller not in buckets:
            buckets[seller] = []
            order.append(seller)
        buckets[seller].append(line)

    groups = []
    for seller in order:
        groups.append(_describe(seller, buckets[seller], can_pay=can_pay))
    return groups


def _describe(
    seller_user_id: int, lines: Sequence[Mapping[str, Any]], *, can_pay: bool = True
) -> dict[str, Any]:
    states = [str(l.get("state") or "") for l in lines]
    blocking = [l for l, state in zip(lines, states)
                if state in BLOCKING_STATES
                or str((l.get("goods_policy") or {}).get("decision") or "ALLOWED") != "ALLOWED"]
    price_changed = [l for l, state in zip(lines, states) if state == "price_changed"]

    currencies = [str(l.get("currency") or "USD").upper() for l in lines]
    currency = currencies[0] if currencies else "USD"
    mixed_currency = any(c != currency for c in currencies)

    kinds = [_line_kind(l) for l in lines]
    scheduled = scheduled_kinds(kinds)
    lane = _lane_question(lines)
    forms = _forms_for(lines, lane.get("kind", ""))

    # The order of these reasons is the order the checkout lane refuses in, so
    # the button explains the first thing the buyer would actually have hit.
    # Availability first, because telling someone to confirm a new price on a line
    # that is also sold out sends them to a dead end; and the unanswerable lane
    # question before the one-at-a-time rule, because the lane's `resolve_choice`
    # loop returns LANE_REQUIRED before it ever reaches its scheduled check.
    reason = ""
    if not can_pay:
        # First, because it is the first thing `cart_checkout` refuses on --
        # `_require_user()` is its opening statement, before it has looked at a
        # single line. Reporting a sold-out line ahead of it would describe a
        # refusal the lane never reaches.
        reason = "Sign in to check out. Your cart comes with you."
    elif blocking:
        reason = ("Some items from this seller are no longer available. "
                  "Remove them to check out.")
    elif price_changed:
        reason = "Confirm the new prices above before you pay."
    elif mixed_currency:
        reason = ("Items priced in different currencies are bought separately. "
                  "The app can split this order.")
    elif not forms:
        # One control, two questions. Nothing here is broken and nothing is sold
        # out; these two lines simply cannot be settled by one answer, and
        # guessing either of them is how someone collecting in person ends up
        # typing an address they never needed.
        reason = ("These items are fulfilled in different ways and cannot be paid "
                  "for together here. The app can check them out separately.")
    elif scheduled and len(lines) > 1:
        reason = ("Bookings, services and events are bought one at a time. "
                  "Check out this item on its own in the app.")
    elif any(k not in BROWSER_KINDS for k in kinds):
        reason = BROWSER_UNSUPPORTED

    # Only meaningful once nothing is price_changed: the lane charges the stored
    # snapshot, and an unconfirmed line's snapshot is the old number. Rather than
    # add up a total the buyer will not be charged, the total is withheld and the
    # reason above says why.
    subtotal = sum(_minor(l.get("price_snapshot_minor")) * _qty(l.get("qty")) for l in lines)

    return {
        "seller_user_id": seller_user_id,
        "seller_store_name": str(
            (lines[0].get("seller_store_name") if lines else "") or "PulseSoc seller"),
        "line_ids": [_minor(l.get("line_id")) for l in lines],
        "item_count": sum(_qty(l.get("qty")) for l in lines),
        "currency": currency,
        "mixed_currency": mixed_currency,
        "subtotal_minor": subtotal,
        "subtotal_final": not price_changed and not mixed_currency,
        "blocking_line_ids": [_minor(l.get("line_id")) for l in blocking],
        "price_changed_line_ids": [_minor(l.get("line_id")) for l in price_changed],
        "checkoutable": not reason,
        "reason": reason,
        # Distinct from `reason` because the two call for different controls.
        # Every other refusal is answered on this page or in the app; this one
        # is answered at `/login`, and offering "Check out in the app" for it
        # would send a visitor to a surface that asks them the same question.
        "sign_in_required": not can_pay,
        "lane_question": lane,
        "forms": forms,
    }
