#!/usr/bin/env python3
"""Freeze the current authentication shape of every registered route.

    python3 scripts/protection/generate_route_auth_baseline.py

Writes `config/route_auth_baseline.json`. Run it, read the diff, and commit the
diff *as part of the change that caused it* — the file is only worth having if
regenerating it is a deliberate act someone reviews, and never a reflex to make
a red test go green.

What the baseline is for, precisely: `tests/protection/test_route_auth.py`
compares today's audit against it and fails on movement. A route that had a gate
and stops having one is the regression it catches. It is not a certification
that the routes in it are safe — see the module docstring of
`services/route_auth.py` for why that distinction is the whole design.

Deliberately *not* wired into CI as an auto-regenerating step. A baseline that
regenerates itself detects nothing.
"""
from __future__ import annotations

import collections
import json
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

OUT = os.path.join(ROOT, "config", "route_auth_baseline.json")

# Importing `bot` runs init_db() against whatever DATABASE_URL says, and it
# resolves that at import and never looks again. Point it at a scratch file
# before the import rather than after, and do it unconditionally: the variable a
# developer already has exported is the one that reaches something real.
os.environ["DATABASE_URL"] = "sqlite:///" + tempfile.mkstemp(
    prefix="route-auth-baseline-", suffix=".db"
)[1]
os.environ.setdefault("FLASK_SECRET_KEY", "route-auth-baseline")

import bot  # noqa: E402
from services import route_auth  # noqa: E402


def _by_endpoint(records: list[dict]) -> dict:
    """Group per-rule audit records under their endpoint.

    `auth`, `evidence` and `declared` are properties of the view function, so
    every record for one endpoint agrees on them and taking the first is safe.
    `rules` and `methods` are properties of the registration and are unioned.
    """
    grouped: dict[str, dict] = {}
    for record in records:
        entry = grouped.setdefault(
            record["endpoint"],
            {
                "rules": [],
                "methods": set(),
                "auth": record["auth"],
                "evidence": record["evidence"],
                "declared": record["declared"],
            },
        )
        entry["rules"].append(record["rule"])
        entry["methods"].update(record["methods"])
    for entry in grouped.values():
        entry["rules"] = sorted(set(entry["rules"]))
        entry["methods"] = sorted(entry["methods"])
    return grouped


def main() -> int:
    undefined = route_auth.undefined_gate_helpers(ROOT)
    if undefined:
        # Refuse rather than write. Every one of those names is a helper the
        # detector believes in and the codebase no longer defines, so the audit
        # about to be frozen would be silently blind for whatever they guarded.
        print(
            "REFUSING to write a baseline: these vocabulary entries define "
            f"nothing in the tree: {undefined}\n"
            "Either they were renamed (update services/route_auth.py to match) "
            "or they were deleted (remove them, and expect the routes they "
            "guarded to need reclassifying).",
            file=sys.stderr,
        )
        return 2

    records = route_auth.audit_app(bot.app)
    counts = collections.Counter(r["auth"] for r in records)
    evidence = collections.Counter(r["evidence"].split(":")[0] for r in records)

    payload = {
        "_README": [
            "Frozen authentication shape of every registered route. Generated by",
            "scripts/protection/generate_route_auth_baseline.py and checked by",
            "tests/protection/test_route_auth.py.",
            "",
            "This is a record of what each route LOOKED LIKE when it was last",
            "reviewed. It is not a statement that these routes are safe. An entry",
            "reading 'unknown' is not an accusation and an entry reading 'user' is",
            "not a guarantee -- see the docstring of services/route_auth.py.",
            "",
            "If a test fails against this file, the question to ask is 'did my",
            "change remove a gate?', not 'how do I regenerate this?'.",
        ],
        "totals": {
            "rules": len(records),
            "by_auth": dict(sorted(counts.items())),
            "by_evidence": dict(sorted(evidence.items())),
        },
        # Keyed by endpoint rather than by rule, because the endpoint is the view
        # and the view is what carries the authentication. But the rules are kept
        # as a list rather than collapsed: one view is routinely registered under
        # several paths (`/api/progress` and `/api/pulse/progress` are the same
        # function), and keeping only the last one seen would mean a deleted
        # alias left no trace in the diff.
        "routes": _by_endpoint(records),
    }

    with open(OUT, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    print(f"  rules      {len(records)}")
    print(f"  by auth    {dict(sorted(counts.items()))}")
    print(f"  by evidence{dict(sorted(evidence.items()))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
