/**
 * Checked-in emoji metadata access + local search (Stages 1-2, 4).
 *
 * Loads src/emoji/data/emoji.json (generated by scripts/generate-emoji-data.mjs
 * from Unicode/CLDR data at dev time). Everything here is synchronous, local
 * and offline — there is no runtime emoji network dependency anywhere.
 */
import type { EmojiCategory, EmojiEntry } from "./types";
import { EMOJI_CATEGORIES } from "./types";
import { stripSkinTone } from "./grapheme";

interface EmojiArtifact {
  version: string;
  count: number;
  emojis: EmojiEntry[];
}

let artifact: EmojiArtifact | null = null;
let byCategory: Map<EmojiCategory, EmojiEntry[]> | null = null;
let byEmoji: Map<string, EmojiEntry> | null = null;

function load(): EmojiArtifact {
  if (!artifact) {
    // Static require so Metro inlines the JSON into the bundle (offline-safe).
    artifact = require("./data/emoji.json") as EmojiArtifact;
  }
  return artifact;
}

/** All emoji in canonical order. */
export function allEmoji(): EmojiEntry[] {
  return load().emojis;
}

/** Dataset provenance string (shown nowhere; used by tests/debug). */
export function emojiDataVersion(): string {
  return load().version;
}

/** Emoji for one canonical category (RECENT is handled by recents.ts). */
export function emojiByCategory(category: EmojiCategory): EmojiEntry[] {
  if (!byCategory) {
    byCategory = new Map();
    for (const cat of EMOJI_CATEGORIES) byCategory.set(cat, []);
    for (const e of load().emojis) byCategory.get(e.category)?.push(e);
  }
  return byCategory.get(category) ?? [];
}

/**
 * Look up the metadata entry for an emoji string. Skin-tone variants resolve
 * to their base entry, so a11y labels and names work for any stored value.
 */
export function findEmoji(emoji: string): EmojiEntry | null {
  if (!byEmoji) {
    byEmoji = new Map();
    for (const e of load().emojis) {
      byEmoji.set(e.emoji, e);
      // Also index the VS16-less form; backends may store either.
      byEmoji.set(e.emoji.replace(/️/g, ""), e);
    }
  }
  return byEmoji.get(emoji) ?? byEmoji.get(emoji.replace(/️/g, "")) ?? byEmoji.get(stripSkinTone(emoji)) ?? null;
}

/**
 * Accessibility label for any emoji value (Stage 19): 😂 → "face with tears
 * of joy", 👍🏿 → the variant name when known. Falls back to the raw string.
 */
export function emojiA11yLabel(emoji: string): string {
  const entry = findEmoji(emoji);
  if (!entry) return emoji;
  if (entry.emoji !== emoji) {
    const variant = entry.variants.find((v) => v.emoji === emoji);
    if (variant) return variant.name;
  }
  return entry.name;
}

/**
 * Local emoji search over names + keywords (Stage 4). Ranking: exact name,
 * name prefix, name substring, keyword prefix, keyword substring. No network.
 */
export function searchEmoji(query: string, limit = 120): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const scored: { e: EmojiEntry; s: number }[] = [];
  for (const e of load().emojis) {
    let s = 0;
    const name = e.name;
    if (name === q) s = 100;
    else if (name.startsWith(q)) s = 80;
    else if (name.includes(q)) s = 60;
    else {
      for (const k of e.keywords) {
        if (k === q) { s = Math.max(s, 70); break; }
        if (k.startsWith(q)) s = Math.max(s, 50);
        else if (k.includes(q)) s = Math.max(s, 30);
      }
    }
    if (s > 0) scored.push({ e, s });
    if (scored.length >= limit * 4) break;
  }
  return scored
    .sort((a, b) => b.s - a.s)
    .slice(0, limit)
    .map((x) => x.e);
}
