#!/usr/bin/env python3
"""Audit PulseSoc backend management command coverage."""

from __future__ import annotations

import json
import os
import sqlite3
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

tmp_db = tempfile.NamedTemporaryFile(prefix="pulsesoc-backend-management-", suffix=".db", delete=False)
tmp_db.close()

os.environ["COINPILOTX_DISABLE_LOCAL_ENV"] = "1"
os.environ["DATABASE_URL"] = f"sqlite:///{tmp_db.name}"
os.environ["SECRET_KEY"] = "backend-management-audit-secret"
os.environ["FLASK_SECRET_KEY"] = "backend-management-audit-secret"
os.environ["SESSION_SECRET"] = "backend-management-audit-secret"
os.environ["FORCE_INIT_DB"] = "1"
os.environ["PULSE_AI_ENABLED"] = "false"

import bot  # noqa: E402
from services import backend_management_registry  # noqa: E402


REPORT_DIR = ROOT / "reports"
REQUIRED_REPORTS = {
    "backend_management_gap_audit.md": "Backend Management Gap Audit",
    "backend_command_center_architecture.md": "Backend Command Center Architecture",
    "backend_management_launch_readiness.md": "Backend Management Launch Readiness",
}


def fail(message: str) -> None:
    print(f"FAIL: {message}")
    raise SystemExit(1)


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def setup_admin() -> None:
    bot.init_db()
    conn = bot.db()
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS admin_users (
            id INTEGER PRIMARY KEY,
            user_id INTEGER,
            email TEXT,
            name TEXT,
            role TEXT,
            status TEXT,
            password_hash TEXT,
            created_at TEXT,
            updated_at TEXT
        )
        """
    )
    cur.execute("PRAGMA table_info(admin_users)")
    columns = {row[1] for row in cur.fetchall()}
    values = {
        "id": 1,
        "user_id": 9901,
        "email": "owner@example.test",
        "name": "Owner Audit",
        "role": "owner",
        "status": "active",
        "password_hash": "not-used",
        "must_change_password": 0,
        "password_changed_at": "2026-06-26T00:00:00",
        "created_at": "2026-06-26T00:00:00",
        "updated_at": "2026-06-26T00:00:00",
    }
    insert_columns = [column for column in values if column in columns]
    placeholders = ", ".join("?" for _ in insert_columns)
    cur.execute(
        f"INSERT OR REPLACE INTO admin_users ({', '.join(insert_columns)}) VALUES ({placeholders})",
        tuple(values[column] for column in insert_columns),
    )
    backend_management_registry.sync_registry(conn)
    conn.commit()
    conn.close()


def client_for_admin() -> object:
    client = bot.webhook_app.test_client()
    with client.session_transaction() as sess:
        sess["admin_user_id"] = 1
    return client


def write_reports() -> None:
    REPORT_DIR.mkdir(exist_ok=True)
    features = backend_management_registry.all_features()
    gaps = backend_management_registry.gap_audit()
    readiness = backend_management_registry.launch_readiness()
    modules = backend_management_registry.category_summary(features)
    standard = backend_management_registry.audit_standard()

    gap_rows = "\n".join(
        f"| `{item.get('feature_key')}` | {item.get('severity')} | {item.get('reason')} | {item.get('route') or ''} |"
        for item in gaps["gaps"]
    ) or "| None | - | No backend management gaps detected. | - |"
    (REPORT_DIR / "backend_management_gap_audit.md").write_text(
        "\n".join([
            "# Backend Management Gap Audit",
            "",
            "Generated by `scripts/backend_management_gap_audit.py`.",
            "",
            f"- Features inventoried: {gaps['total_features']}",
            f"- Gaps found: {gaps['missing_count']}",
            "- Audit scope: backend visibility, permission gates, launch-critical registry coverage, and safe management routes.",
            "",
            "| Feature | Severity | Reason | Route |",
            "| --- | --- | --- | --- |",
            gap_rows,
            "",
            "Remaining partial items are intentionally tracked instead of hidden. They must be completed before those areas are called launch-complete.",
        ]),
        encoding="utf-8",
    )

    module_rows = "\n".join(
        f"| {item['title']} | `{item['category']}` | {item['total']} | {item['active']} | {item['manageable']} | {item['readiness_score']}% | {item['risk_level']} |"
        for item in modules
    )
    required = "\n".join(f"- {item}" for item in standard["required_for_new_features"])
    blockers = "\n".join(f"- {item}" for item in standard["do_not_launch_without"])
    (REPORT_DIR / "backend_command_center_architecture.md").write_text(
        "\n".join([
            "# Backend Command Center Architecture",
            "",
            "PulseSoc now uses `services/backend_management_registry.py` as the permanent backend-management source of truth.",
            "",
            "## Architecture",
            "",
            "- The registry defines feature key, display name, category, route, role, permission, status, owner, backend service, audit log table, risk, launch-critical state, and backend manageability.",
            "- `/admin/command-center` renders role-filtered management modules and department rooms.",
            "- `/admin/command-center/<module>` renders feature-level management inventory.",
            "- `/admin/launch-readiness` shows launch readiness and gaps.",
            "- `/api/admin/backend-management/registry` exposes safe admin-only JSON for diagnostics.",
            "- Registry rows are synced additively into `backend_feature_registry` when the command center loads.",
            "- Audit events can be stored in `backend_management_audit_events` without changing existing feature ownership.",
            "",
            "## Modules",
            "",
            "| Module | Key | Total | Active | Manageable | Readiness | Risk |",
            "| --- | --- | ---: | ---: | ---: | ---: | --- |",
            module_rows,
            "",
            "## Developer Standard",
            "",
            required,
            "",
            "## Launch Blockers For New Features",
            "",
            blockers,
        ]),
        encoding="utf-8",
    )

    (REPORT_DIR / "backend_management_launch_readiness.md").write_text(
        "\n".join([
            "# Backend Management Launch Readiness",
            "",
            f"- Status: {readiness['status']}",
            f"- Score: {readiness['score']}%",
            f"- Critical active: {readiness['critical_active']} / {readiness['critical_total']}",
            f"- Critical partial: {readiness['critical_partial']}",
            f"- Critical blocked: {readiness['critical_blocked']}",
            "",
            "Launch readiness is intentionally conservative: launch-critical features need active backend management and audit coverage.",
            "",
            "## Module Summary",
            "",
            "| Module | Readiness | Gaps | Risk |",
            "| --- | ---: | ---: | --- |",
            "\n".join(f"| {item['title']} | {item['readiness_score']}% | {item['gaps']} | {item['risk_level']} |" for item in readiness["modules"]),
        ]),
        encoding="utf-8",
    )


def run() -> None:
    setup_admin()
    features = backend_management_registry.all_features()
    keys = {item["feature_key"] for item in features}
    for category in backend_management_registry.REQUIRED_MODULES:
        assert_true(any(item["category"] == category for item in features), f"{category} module has registered features")
    for key in (
        "account.profile",
        "account.verification",
        "account.health",
        "account.security",
        "account.settings",
        "account.appeals",
        "account.audit_logs",
        "account.restrictions",
        "account.sessions",
        "account.devices",
    ):
        assert_true(key in keys, f"{key} exists in registry")
    for item in features:
        assert_true(item["feature_key"] and "." in item["feature_key"], f"{item['display_name']} has stable feature key")
        assert_true(item["category"] in backend_management_registry.REQUIRED_MODULES, f"{item['feature_key']} category valid")
        assert_true(item["status"] in backend_management_registry.STATUSES, f"{item['feature_key']} status valid")
        assert_true(item["risk_level"] in backend_management_registry.RISK_LEVELS, f"{item['feature_key']} risk valid")
        assert_true(bool(item["route"]), f"{item['feature_key']} has route")
        serialized = json.dumps(item).lower()
        for secret_word in ("private_key", "database_url", "secret", "token", "password_hash"):
            assert_true(secret_word not in serialized, f"{item['feature_key']} does not expose {secret_word}")

    conn = bot.db()
    cur = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM backend_feature_registry")
    assert_true(int(cur.fetchone()[0]) >= len(features), "registry synced to backend_feature_registry")
    conn.close()

    client = client_for_admin()
    for path in ("/admin/command-center", "/admin/command-center/account", "/admin/launch-readiness"):
        response = client.get(path)
        assert_true(response.status_code == 200, f"{path} loads for owner")
    payload = client.get("/api/admin/backend-management/registry").get_json() or {}
    assert_true(payload.get("ok") is True, "registry API returns ok")
    assert_true(any(item["category"] == "account" for item in payload.get("features", [])), "registry API includes account module")

    public_client = bot.webhook_app.test_client()
    assert_true(public_client.get("/api/admin/backend-management/registry").status_code in {302, 401, 403}, "public registry API blocked")
    assert_true(public_client.get("/admin/launch-readiness").status_code in {302, 401, 403}, "public launch readiness blocked")

    write_reports()
    for filename in REQUIRED_REPORTS:
        assert_true((REPORT_DIR / filename).exists(), f"{filename} report generated")
    print("PASS: Backend management gap audit passed")


if __name__ == "__main__":
    try:
        run()
    finally:
        try:
            Path(tmp_db.name).unlink(missing_ok=True)
        except Exception:
            pass
